name: Deploy VitePress to Server

on:
  push:
    branches:
      - main  # Déclenchement à chaque push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod-ovh

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Générer le site statique
        run: npm run docs:build

      - name: Déployer via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /www/perso/
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
